### ISSUE TITLE
[JOSS] Community Guidelines

### ISSUE THREAD

**Issue by gcattan** [gdede-hua/Decision_Survey_Platform#1]
# Issue https://github.com/openjournals/joss-reviews/issues/4403

Please, add community guidelines to the Github:

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by gdede-hua** [comment]
@gcattan Thank you for your feedback.
Please be kindly informed that the readme file has been updated and further guidelines are included as per your comments.
