### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by fabian-s** [gdede-hua/Decision_Survey_Platform#10]
https://github.com/openjournals/joss-reviews/issues/4403

@rreinecke 
this commit:
https://github.com/gdede-hua/Decision_Survey_Platform/commit/5fadffb8263bfc23c4da80735037a6bc5f166e25
added/extended unit tests AFAICT -- do these satisfy your concerns re. the lack of automated testing?

**Comment by rreinecke** [comment]
I think it could still be improved but it is certainly  start. Thank you for implementing this.
If you like close this issue.
