### ISSUE TITLE
[JOSS] Add tests and test coverage

### ISSUE THREAD

**Issue by gcattan** [gdede-hua/Decision_Survey_Platform#2]
# Issue https://github.com/openjournals/joss-reviews/issues/4403

Please, add automated tests and test coverage to this repository:

> Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by gdede-hua** [comment]
@gcattan Thank you for your feedback.
Please be kindly informed that the manual steps describing the main functionalities are presented in the readme file. Following these steps one may verify the software functionalities. Is that ok?

**Comment by gcattan** [comment]
You need to provide evidence that the software works as expected, and to provide a mechanism to guarantee that any further changes will not break its behavior.
if you do not want to write automated tests for this, you can write high-level user stories in Gherkin syntax for example, or provide detailed tutorials that you can use later for functional validation testing.
The pictures in the readme do not provide information on whether or not the computation is _correct_.

**Comment by rreinecke** [comment]
openjournals/joss-reviews#4403

**Comment by gdede-hua** [comment]
Dear @gcattan please be kindly informed that we have performed some JUnit tests included in the test folder.

**Comment by gcattan** [comment]
Ok, thank you for the update. I believe the work is now compliant with the JOSS criterion. 
As a side comment (I leave it to you), I think it could be a good idea to run these tests into a pipeline.
