### ISSUE TITLE
Example usage: Add an example use-case

### ISSUE THREAD

**Issue by rreinecke** [gdede-hua/Decision_Survey_Platform#3]
You provide a quite extensive intro with screenshots on how to add users etc. but there is no explanation on how the tool  then can then be used to solve a real problem. Please add a (simple) example that showcases the use of the tool. 

openjournals/joss-reviews#4403

**Comment by gdede-hua** [comment]
Dear @rreinecke thank you for your feedback. The paper.md has been updated as per your suggestion and now includes a  real case as an example.

**Comment by rreinecke** [comment]
Great! I am not sure the paper.md is the right place (because it is quite extensive - which is good! Really helped me to understand). I am ok leaving it there if the JOSS editor agrees. Otherwise I would suggest moving it to you user documentation or readme file.

**Comment by fabian-s** [comment]
@gdede-hua JOSS aims for papers <1000 words, you're now at  ~1900. 
Please move the case study out of the paper and reference it there.

see also #9

**Comment by fabian-s** [comment]
please also note that these reviews become a lot simpler for us reviewers/editors if your commit messages explicitly reference the respective issues they are meant to fix, or if your messages in these issue threads explicitly reference the commits that were intended to fix them.

**Comment by gdede-hua** [comment]
Dears, please be kindly informed that the case study has been moved to the readme file.

**Comment by fabian-s** [comment]
@rreinecke please close this issue if you are satisfied with the example

**Comment by rreinecke** [comment]
the examples contains a typo in line three with one point too much.

Apart from that can a potential user download that scenario and look at the results? Then you could shorten the text a bit and users could try it out themself. I think that would be helpful. Also at least one screenshot of how the results look like would be good. Currently it is outline an example but does not really demonstrate on how your tool then processes the described example and how that would be helpful. Or is the tool really just about collecting the decisions? If so then I think a potential result figure would still be helpful I think.

**Comment by rreinecke** [comment]
I will close this issue still now. I think it is in your own interest to improve this further.
