### ISSUE TITLE
Add demo data and describe API ports

### ISSUE THREAD

**Issue by gcattan** [gdede-hua/Decision_Survey_Platform#6]
As per: https://github.com/openjournals/joss-reviews/issues/4403#issuecomment-1156833231

**Comment by gdede-hua** [comment]
Dear @gcattan the ports are now included in the readme file.

The description on how to use the platform both as an administrator and as a user (how to add data) is also described in the readme file. You may also find the credentials for the default accounts of administrator and user.

**Comment by gcattan** [comment]
Ok. Thank you for the update.
