### ISSUE TITLE
Add note on browser path

### ISSUE THREAD

**Issue by rreinecke** [gdede-hua/Decision_Survey_Platform#7]
An inexperienced user would not know that they have to open their browser to go to http://localhost:8080 
I suggest adding that to the install documentation.

**Comment by gdede-hua** [comment]
Dear @rreinecke please be informed that the link of the application is now included in the installation section of the readme.

**Comment by fabian-s** [comment]
@gdede-hua please provide the specific commit(s) that contain(s) this change
@rreinecke please close this issue if you are satisfied.

**Comment by gdede-hua** [comment]
Commit: https://github.com/gdede-hua/Decision_Survey_Platform/commit/5730fb075a3cae61f6a602ece22a8e7ba06d4f91
