### ISSUE TITLE
paper is too long for JOSS

### ISSUE THREAD

**Issue by fabian-s** [gdede-hua/Decision_Survey_Platform#9]
JOSS aims for papers <1000 words, you're now at  ~1900. 
Please move the case study out of the paper into a file hosted in your repo, and reference it in your paper. (no need to remove anything else)

see also https://github.com/openjournals/joss-reviews/issues/4403

**Comment by gdede-hua** [comment]
Dear @fabian-s please be informed that the case study has been removed from the paper and it is now included in readme.

**Comment by fabian-s** [comment]
Thanks, good enough
